when@dev:
    web_profiler:
        toolbar: true
        intercept_redirects: false
        excluded_ajax_paths: '^/(app(_[\\w]+)?\\.php/)?(api/doc|api/doc\\.json)'

    framework:
        profiler:
            only_exceptions: false
            collect_serializer_data: true

when@test:
    web_profiler:
        toolbar: false
        intercept_redirects: false

    framework:
        profiler: { collect: false }

web_profiler:
    toolbar: true
    intercept_redirects: false
